version: "3"

dotenv: ["_build/build.env"]

tasks:
  build-debug:
    desc: Build with debug symbols for the current platform.
    summary: |
      Build with debug symbols for the current platform.
    cmds:
      - >
        go build
        -gcflags="all=-N -l"
        -ldflags="-X marcuson/scriptman/internal/cliapp.Version={{.SCRIPTMAN_VERSION}}"
        -o ./_build/debug_bin ./cmd/scriptman
    sources:
      - cmd/**/*.go
      - internal/**/*.go
    generates:
      - _build/debug_bin

  build-linux:
    desc: Production build for Linux.
    summary: |
      Production build for Linux.
    cmds:
      - >
        GOOS=linux GOARCH=amd64 go build
        -gcflags="all=-N -l"
        -ldflags="-X marcuson/scriptman/internal/cliapp.Version={{.SCRIPTMAN_VERSION}} -s -w"
        -o ./_build/linux/sman ./cmd/scriptman
    sources:
      - cmd/**/*.go
      - internal/**/*.go
    generates:
      - _build/linux/sman

  build-windows:
    desc: Production build for Windows.
    summary: |
      Production build for Windows.
    cmds:
      - >
        GOOS=windows GOARCH=amd64 go build
        -gcflags="all=-N -l"
        -ldflags="-X marcuson/scriptman/internal/cliapp.Version={{.SCRIPTMAN_VERSION}} -s -w"
        -o ./_build/windows/sman ./cmd/scriptman
    sources:
      - cmd/**/*.go
      - internal/**/*.go
    generates:
      - _build/windows/sman

  build-all:
    desc: Production build for all supported platforms.
    summary: |
      Production build for all supported platforms.
    cmds:
      - task: build-linux
      - task: build-windows

  clean:
    desc: Clean temp artifacts.
    summary: |
      Clean temp artifacts.
    cmds:
      - go run ./scripts/clean

  run:
    desc: Run app on current platform.
    summary: |
      Run app on current platform.
    vars:
      SCRIPTMAN_VERSION: '{{.SCRIPTMAN_VERSION | default "X.Y.Z"}}'
    cmds:
      - go run ./cmd/scriptman --help

  set-version:
    desc: Set version for next build.
    summary: |
      Set version for next build.
    cmds:
      - >
        go run ./scripts/set-version {{.VER}}

  generate:
    desc: Automatically generate support files based on directives.
    summary: |
      Automatically generate support files based on directives.
    cmds:
      - docker run -v "{{.ROOT_DIR}}":/src -w /src vektra/mockery --all

  test:
    desc: Run all tests.
    summary: |
      Run all tests.
    cmds:
      - go test ./...
