# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release-all:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check env
      run: |
        echo "Github repo: $GITHUB_REPOSITORY"
          
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Set up Taskfile
      uses: rnorton5432/setup-task@v1
      with:
        task-version: 3.37.2

    - name: Release
      uses: codfish/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
